baseURL = "https://mb.frogren.se"
languageCode = "sv"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "Mikroblogg"
    signature = "jfrogren"
    cover = "https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_1280.jpg"

    name = "jfrogren"
    avatar = "/img/foto-med-hatt.png"
